# This is a basic workflow to help you get started with Actions

name: First-action

on:
  commit_comment:
    branches: [ master, web ]
    
jobs:
  build:
    runs-on: windows
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        name: 'setup node'
        with: 
          node-version: '13x'
      
      - name: 'install'
        run: npm i
        
      - name: 'branch web'
        run: git branch web
